apiVersion: apps/v1
kind: Deployment
metadata:
  name: standard-producer
  namespace: stress
  labels:
    app.kubernetes.io/name: standard-producer
    app.kubernetes.io/part-of: stress
spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: standard-producer
      app.kubernetes.io/part-of: stress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: standard-producer
        app.kubernetes.io/part-of: stress
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "dedicated"
                    operator: "In"
                    values:
                      - "s2-loadtest"
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "s2-loadtest"
          effect: "NoSchedule"
      containers:
        - name: standard-producer
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          image: ghcr.io/s2-streamstore/stress-stream-rs@sha256:b5de468a0e40f13666d7a4c2d34bd91c4f488645e0b398063d53eb07a68a9307
          ports:
            - name: metrics
              containerPort: 8000
          env:
            - name: RUST_LOG
              value: "info"
            - name: S2_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: s2-auth-token
                  key: s2-auth-token
          command:
            - "producer"
            - "--basin"
            - "stress-rs"
            - "--stream"
            - "standard"
            - "--throughput"
            - "10485760"
            - "--avg-record-size"
            - "1024"
            - "--avg-batch-size"
            - "500"
            - "--randomize"
