apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pod-monitor
  namespace: stress
  labels:
    app.kubernetes.io/name: pod-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: stress
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
